#pragma once

enum EOBJCLASS { ENVIRONMENT , MATERIAL, EQUIPMENT, ERECTION };
enum EOBJKIND_ENVIRONMENT {FLOWER, TREE1, TREE2, RASPBERRYSTACK, ROCK, HAYSTACK/*°ÇÃÊ´õ¹Ì*/};
enum EOBJKIND_MATERIAL { FLINT/*ºÎ½Ëµ¹*/, STONE, CARROT, RASPBERRY, BRANCH, LOG, HAY};
enum EOBJKIND_EQUIPMENT {AXE, PICKAX/*°î±ªÀÌ*/, TORCH/*È¶ºÒ*/, BAG};
enum EOBJKIND_ERECTION {BONFIRE/*¸ð´ÚºÒ*/, STORAGE/*ÀúÀå¼Ò*/};

enum EOBJECT_IN_INVENTORY_KIND {};

struct OBJECT_IN_INVENTORY {
	EOBJECT_IN_INVENTORY_KIND _kind;
	int _num; // °¹¼ö ¶Ç´Â ³»±¸µµ
};

enum EOBJ_ENVIRONMENT_STATE {
	EES_IDLE,
	EES_DEAD,
	EES_LEFTDYING,
	EES_RIGHTDYING,
	EES_CHOPPED,
	EES_DELETE
};